name: "Package"
on:
  push:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'
          includePrerelease: true
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: |
          sudo mkdir -p /nix/store
          sudo chmod -R 777 /nix
      - name: Cache nix env take N+1
        uses: actions/cache@v2
        with:
          path: |
            /nix/store/**
            /nix/var/nix/*/*
            /nix/var/nix/db/*
            /nix/var/nix/db/*/**
            !/nix/var/nix/daemon-socket/socket
            !/nix/var/nix/userpool/*
            !/nix/var/nix/gc.lock
            !/nix/var/nix/db/big-lock
            !/nix/var/nix/db/reserved
          key: ${{ runner.os }}-nix-store
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: programmerino
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10
      - run: nix build --impure -L
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "${{ steps.gitversion.outputs.semVer}}"
          automatic_release_tag: "${{ steps.gitversion.outputs.semVer}}"
          prerelease: ${{ steps.gitversion.outputs.preReleaseLabel != '' }}
          files: |
            ./result/*.tar.gz